[features]
seeds = false
skip-lint = false
[programs.devnet]
contract_maker = "B1QiqgAYGcsL2HPTLxATxASh8Py6SAX1TBPUzynDvcyC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/teamgreen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
